In [ ]:
#exercise_1

In [64]:
import numpy as np

a=int(input("Mulai:"))
b=int(input("Selesai:"))
arr=np.arange(a,b)
arr2=arr.reshape(3,9)
arr3=arr2.reshape(3,3,3)



Mulai:1
Selesai:28


In [66]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [67]:
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [68]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [61]:
#Exercise_2

In [70]:
import random
import numpy as np

In [71]:
#input
a=int(input("Banyak data:"))
b=int(input("Mulai:"))
c=int(input("Selesai:"))

Banyak data:16
Mulai:1
Selesai:50


In [74]:
arr=np.random.randint(b,c,a)
arr



array([14, 18, 25, 37, 26, 27,  9, 20, 37, 21,  7, 45, 31,  6,  4, 21])

In [76]:
duadim = arr.reshape(4,4)
duadim

array([[14, 18, 25, 37],
       [26, 27,  9, 20],
       [37, 21,  7, 45],
       [31,  6,  4, 21]])

In [78]:
duadim[:,::-1]

array([[37, 25, 18, 14],
       [20,  9, 27, 26],
       [45,  7, 21, 37],
       [21,  4,  6, 31]])

In [79]:
#Exercise_3

In [80]:
x= np.ones((10,10))*4
x[1:-1,1:-1]=0
x


array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])